rm(list = ls())
library(data.table)
library(stargazer)
library(ggplot2)
library(ivreg)
#library(lubridate)
#library(haven)
#library(readr)
#library(gmm)
#library(texreg)
#library(xtable)
#library(modelsummary)

setwd(dirname(rstudioapi::getActiveDocumentContext()$path))

set.seed(123)
options(digits = 5, scipen = 4)