---
title: 'IO2 PS2: Bresnahan and Reiss (1991)'
author: "Carlos T. Estrada Arzamendi"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  pdf_document:
    extra_dependencies: float
    keep_tex: true
keep_tex: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list = ls())
library(data.table)
library(stargazer)
library(ggplot2)
library(modelsummary)

set.seed(123)
options(digits = 5, scipen = 4)
```

# Problem 1 : 
Reproduce the results for the tire dealers reported in Table 4 of the paper. Note that
Bresnahan and Reiss (1991) estimate the model imposing the constraints $\alpha_n \geq 0$ and
$\gamma_n \geq 0$. You should impose the same constraints.
```{r data}
# Reading Data
data = as.data.table(read.csv("ps2.csv"))
```

## Reproducing Figure 2 to get to know the data
```{r figure2, out.width = "70%", fig.align = 'center'}
figure2 = ggplot(data, aes(x = TPOP)) + geom_histogram(breaks = seq(0,7.5, by = 0.5)) +
              scale_x_continuous(limits = c(0, 7.5),
                     oob = scales::oob_squish) +
            xlab("Town Population (thousands)") +
            ylab("Number of Towns") +
            ggtitle("Number of towns by town population")
figure2
```
## Table 3
```{r}
datasummary_skim(data, out = "markdown", histogram = F, title = "Table 3")
```

## Table 4
```{r}
loglike = function(par, x){
lambda = par[1:4]
beta = par[5:8]
alpha = par[9:13]
gamma = par[14:19]


}
```