---
title: 'IO2 PS2: Bresnahan and Reiss (1991)'
author:
  - name: Carlos T. Estrada Arzamendi
date: today
date-format: long
format:
    pdf:
        geometry:
          - top =  1in
          - left = 0.8in
          - right =  0.8in
        colorlinks: true
        keep-tex: true
fig-align: center
editor: visual
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list = ls())
library(data.table)
library(stargazer)
library(ggplot2)
library(modelsummary)

set.seed(123)
options(digits = 5, scipen = 5)
```

# Problem 1 :

Reproduce the results for the tire dealers reported in Table 4 of the paper. Note that Bresnahan and Reiss (1991) estimate the model imposing the constraints $\alpha_n \geq 0$ and $\gamma_n \geq 0$. You should impose the same constraints.

```{r data}
# Reading Data
data = as.data.table(read.csv("ps2.csv"))
```

## Reproducing Figure 2 to get to know the data

```{r figure2, out.width = "60%", fig.align = 'center', fig.cap = "Number of towns by town population"}
figure2 = ggplot(data, aes(x = TPOP)) + 
                geom_histogram(breaks = seq(0,7.5, by = 0.5)) + 
                scale_x_continuous(limits = c(0, 7.5), oob = scales::oob_squish) +
                xlab("Town Population (thousands)") +
                ylab("Number of Towns")
figure2
```

## Reproducing Table 3 to get to know the data

```{r}
datasummary_skim(data, out = "markdown", histogram = F, title = "Replication of Table 3")
```

## Table 4

```{r}
loglike = function(par, x){
lambda = par[1:4]
beta = par[5:8]
alpha = par[9:13]
gamma = par[14:19]

s = x$TPOP + lambda[1]*x$NRGW + lambda[2]*x$PGRW + lambda[3]*x$OCTY + lambda[4]*x$OPOP


}
```

Does this bring up the terminal?